/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerationRouteImport } from './routes/generation'
import { Route as IndexRouteImport } from './routes/index'

const GenerationRoute = GenerationRouteImport.update({
  id: '/generation',
  path: '/generation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generation': typeof GenerationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generation': typeof GenerationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generation': typeof GenerationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generation'
  id: '__root__' | '/' | '/generation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerationRoute: typeof GenerationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generation': {
      id: '/generation'
      path: '/generation'
      fullPath: '/generation'
      preLoaderRoute: typeof GenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerationRoute: GenerationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
